# Airborne MAVLink input configuration.
# UDP receiver:
MAVLINK_LISTEN="udpin:0.0.0.0:14550"

# TCP server example:
# MAVLINK_LISTEN="tcpin:0.0.0.0:5760"

# Serial examples:
# MAVLINK_LISTEN="/dev/ttyUSB0"
# MAVLINK_LISTEN="/dev/ttyS4"

MAVLINK_BAUD=115200
MAVLINK_SYSTEM_ID=1
MAVLINK_COMPONENT_ID=191
